### ISSUE TITLE
Home Page: Collaboration/Maps Section

### ISSUE THREAD

**Issue by mhaidarhanif** [reactjs-id/website-remix#4]
![Image](https://github.com/reactjs-id/website-remix/assets/235584/3be8c364-6629-43e8-bd2d-1052528f8e48)

**Comment by andihaki** [comment]
picked up ya @mhaidarhanif 🎉 
https://github.com/reactjs-id/website-remix/pull/22

**Comment by mhaidarhanif** [comment]
Will be improved again later.
