### ISSUE TITLE
Home Page: Hero Details

### ISSUE THREAD

**Issue by mhaidarhanif** [reactjs-id/website-remix#7]
Expectation:

![Image](https://github.com/reactjs-id/website-remix/assets/235584/6526f50a-319c-4630-ad4a-e8f7ade1fbb5)

Reality:

![Image](https://github.com/reactjs-id/website-remix/assets/235584/de1d727d-80fd-4e67-a32d-ed0540287d7d)

**Comment by andihaki** [comment]
@mhaidarhanif picked Hero Details Task: https://github.com/reactjs-id/website-remix/pull/15

**Comment by mhaidarhanif** [comment]
Will be improved again later.
